	<html>
	    <head>
	        <meta charset="utf-8">
	        <meta name="robots" content="noindex, nofollow, noarchive">
			<title>SIMON .: Welcome! :.</title>
			<link href="//fonts.googleapis.com/css?family=opensans:500" rel="stylesheet" type="text/css">
	        <link rel="stylesheet" href="/assets/main.css">
	    </head>
	    <body>
	        <div id="genular_logo"></div>
	        <div id="footer">made with ❤️ by
	            <a href="https://genular.org" target="_blank">genular</a>
	        </div>
	    </body>
	</html>